version: "3"
services:
  mysql:
    image: mysql/mysql-server
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
  php-cli:
    build: .
  